import React from 'react'
import Head from 'next/head'
import ContactForm from '@/components/ContactForm'
import Navbar from '@/components/Navbar'
import Social from '@/components/Social'
import Bg from '@/components/Bg'
const Contact = () => {
  return (<>
    <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logow.svg" />
      </Head>
  <Navbar/>
  <Bg/>
  <Social/>
 <ContactForm/>
    </>
  )
}

export default Contact