import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Social from '@/components/Social'
const Project = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Social/>
    <div className='w-[1000px] mx-auto mt-[75px]'>
  <div className=' flex justify-evenly items-center '>
    
     <div className='w-[300px] h-[250px]  bg-white rounded-lg shadow-xl overflow-hidden p-animate border-t-[3px] border-cyan-500'></div>
     <div className='flex flex-col'>
     <div className='w-[300px]  bg-white rounded-lg shadow-xl overflow-hidden h-[250px] d1 border-t-[3px] border-green-600'></div>
     <div className='w-[300px] mt-[25px]  bg-white rounded-lg shadow-xl overflow-hidden h-[250px] d2 border-t-[3px] border-yellow-500'></div>
     </div>
     <div className='w-[300px]  bg-white rounded-lg shadow-xl overflow-hidden f-animate h-[250px] border-t-[3px] border-red-500'></div>
    </div>
    </div>
    </>
  )
}

export default Project