import React from 'react'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Social from '@/components/Social'
import Link from "next/link";

const Project = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Social/>
    <div className='w-[1000px] mx-auto mt-[75px]'>
  <div className=' flex justify-evenly items-center '>
    
     <div className='w-[300px] h-[250px]  bg-white rounded-lg shadow-xl overflow-hidden p-animate border-t-[3px] border-cyan-500'>
      <div className='mx-6 mt-8'>
      <h2 className='font-extrabold text-lg'>MENU TRACKER</h2>
      <p className='text-base pt-2'>It is a menu tracking system that tracks items ordered by the customers. Implemented using Next.js and Typescript with React.js.
      </p>
      <div className='pt-4'>
      <Link href='https://github.com/abish-desu/MenuTracker' >
      <button className="px-6 py-2  text-sm bg-slate-700 text-white rounded-md shadow-sm hover:scale-105 ase-in-out duration-75">View</button>
      </Link></div>


</div>
     </div>
     <div className='flex flex-col'>
     <div className='w-[300px]  bg-white rounded-lg shadow-xl overflow-hidden h-[250px] d1 border-t-[3px] border-green-600'>
     <div className='mx-6 mt-8'>
      <h2 className='font-extrabold text-lg'>PORTFOLIO</h2>
      <p className='text-base pt-2'>Personal portfolio website built with Next.js and React.js.
      </p>
      <div className='pt-4'>
      <Link href='https://github.com/abish-desu/portfolio-next' >
      <button className="px-6 py-2  text-sm bg-slate-700 text-white rounded-md shadow-sm hover:scale-105 ase-in-out duration-75">View</button>
      </Link>      </div>


</div>
     </div>
     <div className='w-[300px] mt-[25px]  bg-white rounded-lg shadow-xl overflow-hidden h-[250px] d2 border-t-[3px] border-yellow-500'>
     <div className='mx-6 mt-8'>
      <h2 className='font-extrabold text-lg'>WEATHER APP</h2>
      <p className='text-base pt-2'>It is a weather app which displays weather status of the current location. Implemented using React.js.
      </p>
      <div className='pt-4'>
        <Link href='https://github.com/abish-desu/weather-app' >
      <button className="px-6 py-2  text-sm bg-slate-700 text-white rounded-md shadow-sm hover:scale-105 ase-in-out duration-75">View</button>
      </Link>
      </div>


</div>
     </div>
     </div>
     <div className='w-[300px]  bg-white rounded-lg shadow-xl overflow-hidden f-animate h-[250px] border-t-[3px] border-red-500'>
     <div className='mx-6 mt-8'>
      <h2 className='font-extrabold text-lg'>DISCORD BOT</h2>
      <p className='text-base pt-2'>
      Guess The Jumble Word Game Bot!. Implemented using Javascript and Discord.js.
      </p>
      <div className='pt-4'>
      <Link href='https://github.com/abish-desu/discord-game-bot' >
      <button className="px-6 py-2  text-sm bg-slate-700 text-white rounded-md shadow-sm hover:scale-105 ase-in-out duration-75">View</button>
      </Link>      </div>


</div>
     </div>
    </div>
    </div>
    </>
  )
}

export default Project