import React from "react";
import Navbar from "@/components/Navbar";
import Social from "@/components/Social";
import Head from "next/head";
import Bg from "@/components/Bg";

const About = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" className='filter invert-100' href="/logow.svg" />
      </Head>
    <Navbar/>
    <Bg/>
    <Social/>
    <div className='relative flex justify-center items-center h-[35rem]'>
     <p className= "text-5xl font-thin text-[#a0a0a0]">I DONT KNOW ABOUT MYSELF</p>
    </div>
  
    </>
  );
};

export default About;
