import React from 'react'
import Navbar from '@/components/Navbar'
import Social from '@/components/Social'
import Head from 'next/head'

const Blogs = () => {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Social/>
    <div className='relative flex justify-center items-center h-[35rem]'>
     <h1 className= "text-7xl text-[#909090]">404 :/</h1>
    </div>
    </>
  )
}

export default Blogs