import React from 'react'
import Navbar from '@/components/Navbar'
import Social from '@/components/Social'
import Head from 'next/head'

const Blogs = () => {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Social/>
    <div>Blogs</div>
    </>
  )
}

export default Blogs